/bin/bash: /cluster/customapps/biomed/grlab/users/eglimar/conda/envs/inf-extr/lib/libtinfo.so.6: no version information available (required by /bin/bash)
/cluster/home/eglimar/.env_bootstrap/dotfiles/shell/bashrc: line 17: module: command not found
/cluster/home/eglimar/.env_bootstrap/dotfiles/shell/bashrc: line 20: module: command not found
Traceback (most recent call last):
  File "/cluster/home/eglimar/inf-extr/scripts/llama2-finetune/finetune.py", line 236, in <module>
    main()
  File "/cluster/home/eglimar/inf-extr/scripts/llama2-finetune/finetune.py", line 51, in main
    args = parse_args()
           ^^^^^^^^^^^^
  File "/cluster/home/eglimar/inf-extr/scripts/llama2-finetune/finetune.py", line 37, in parse_args
    parser.add_argument("--bf16", type=bool, action="store_true", help="Enable bf16 training. Defaults to False")
  File "/cluster/customapps/biomed/grlab/users/eglimar/conda/lib/python3.11/argparse.py", line 1450, in add_argument
    action = action_class(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
TypeError: _StoreTrueAction.__init__() got an unexpected keyword argument 'type'
