/bin/bash: /cluster/customapps/biomed/grlab/users/eglimar/conda/envs/inf-extr/lib/libtinfo.so.6: no version information available (required by /bin/bash)
/cluster/home/eglimar/.env_bootstrap/dotfiles/shell/bashrc: line 17: module: command not found
/cluster/home/eglimar/.env_bootstrap/dotfiles/shell/bashrc: line 20: module: command not found
Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]Loading checkpoint shards:  33%|███▎      | 1/3 [00:58<01:57, 58.94s/it]Loading checkpoint shards:  67%|██████▋   | 2/3 [02:06<01:04, 64.14s/it]Loading checkpoint shards: 100%|██████████| 3/3 [02:42<00:00, 51.29s/it]Loading checkpoint shards: 100%|██████████| 3/3 [02:42<00:00, 54.25s/it]
Generating train split: 0 examples [00:00, ? examples/s]Generating train split: 302 examples [00:00, 1851.18 examples/s]
/cluster/customapps/biomed/grlab/users/eglimar/software/virtualenvs/inf-extr-RuZI_Gck-py3.11/lib/python3.11/site-packages/trl/trainer/sft_trainer.py:294: UserWarning: You passed a tokenizer with `padding_side` not equal to `right` to the SFTTrainer. This might lead to some unexpected behaviour due to overflow issues when training a model in half-precision. You might consider adding `tokenizer.padding_side = 'right'` to your code.
  warnings.warn(
Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
  0%|          | 0/19 [00:00<?, ?it/s]  5%|▌         | 1/19 [00:14<04:26, 14.78s/it] 11%|█         | 2/19 [00:26<03:37, 12.77s/it] 16%|█▌        | 3/19 [00:37<03:14, 12.14s/it] 21%|██        | 4/19 [00:48<02:57, 11.86s/it] 26%|██▋       | 5/19 [01:00<02:43, 11.71s/it] 32%|███▏      | 6/19 [01:11<02:31, 11.63s/it] 37%|███▋      | 7/19 [01:23<02:18, 11.58s/it] 42%|████▏     | 8/19 [01:34<02:07, 11.55s/it] 47%|████▋     | 9/19 [01:46<01:55, 11.53s/it] 53%|█████▎    | 10/19 [01:57<01:43, 11.52s/it] 58%|█████▊    | 11/19 [02:09<01:32, 11.52s/it] 63%|██████▎   | 12/19 [02:20<01:20, 11.51s/it] 68%|██████▊   | 13/19 [02:32<01:09, 11.52s/it] 74%|███████▎  | 14/19 [02:43<00:57, 11.52s/it] 79%|███████▉  | 15/19 [02:55<00:46, 11.52s/it] 84%|████████▍ | 16/19 [03:06<00:34, 11.52s/it] 89%|████████▉ | 17/19 [03:18<00:23, 11.52s/it] 95%|█████████▍| 18/19 [03:30<00:11, 11.53s/it]100%|██████████| 19/19 [03:40<00:00, 11.17s/it]                                               100%|██████████| 19/19 [03:40<00:00, 11.17s/it]100%|██████████| 19/19 [03:40<00:00, 11.60s/it]
/cluster/customapps/biomed/grlab/users/eglimar/software/virtualenvs/inf-extr-RuZI_Gck-py3.11/lib/python3.11/site-packages/peft/utils/save_and_load.py:154: UserWarning: Could not find a config file in /cluster/dataset/midatams/inf-extr/resources/models/Llama2-MedTuned-13b - will assume that the vocabulary was not modified.
  warnings.warn(
